grid: DilationAblationMioU

parameters:
  model: [dcama]
  explainer:
    name: [masked_affinity, signed_affinity]
    mask_dilation_radius: [1, 3, 5]
    mask_dilation_kernel: [3, 5, 7]
    
  explanation_masking: [logits]
  log_frequency: [50]

  metric:
    n_steps: [1]
    substrate_fn: [zero]
    percentage: [0.01]
    measure: [miou]
    loss: [True]
    skip_empty: [True]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      val_pascal5i_N1K5:
        name: [pascal]
        data_dir: &instance_dir [data/pascal]
        split: ["val"]
        val_fold_idx: [null]
        n_folds: [4]
        n_shots: [5]
        n_ways: [1]
        do_subsample: [False]
        val_num_samples: [1000]
        maintain_gt_shape: [False]
    common:
      remove_small_annotations: [True]
      custom_preprocess: [False]
      maintain_gt_shape: [False]
  dataloader:
    num_workers: [16]
    batch_size: [1]
    csv_folder: [data_csv]

other_grids:
