grid: FirstGrid

parameters:
  model: [dcama]
  explainer:
    name: [random, affinity, integrated_gradients, saliency]

  explanation_masking: [ground_truth, logits]
  log_frequency: [50]

  metric:
    step: [1000]
    substrate_fn: [zero]

  num_processes: [10]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      val_pascal5i_N1K5:
        name: [pascal]
        data_dir: &instance_dir [data/pascal]
        split: ["val"]
        val_fold_idx: [null]
        n_folds: [4]
        n_shots: [5]
        n_ways: [1]
        do_subsample: [False]
        val_num_samples: [1000]
        maintain_gt_shape: [False]
    common:
      remove_small_annotations: [True]
      ignore_borders: [True]
      custom_preprocess: [False]
  dataloader:
    num_workers: [16]
    batch_size: [1]
