grid: CUTIAUC_Coco_N1K1

parameters:
  model: [dcama]
  explainer:
    name:
      [
        random,
        gaussian_noise,
        saliency,
        integrated_gradients,
        guided_ig,
        blur_ig,
        xrai,
        deep_lift,
        lime,
        affinity,
        masked_affinity,
        signed_affinity,
      ]

  explanation_masking: [logits]
  # metric_masking: [all]
  log_frequency: [50]
  disable_dauc: [True]

  device: [cuda:0]
  cache: [False]
  
  metric:
    n_steps: [5]
    substrate_fn: [zero]
    percentage: [0.01]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      val_coco20i_N1K1:
        name: [coco]
        instances_path: [data/coco/annotations/instances_val2014.json]
        all_example_categories: [False]
        img_dir: [data/coco/train_val_2017]
        n_shots: [1]
        n_ways: [1]
        do_subsample: [False]
        add_box_noise: [False]
        val_fold_idx: [null]
        n_folds: [null]
        split: ["val"]
    common:
      remove_small_annotations: [True]
      custom_preprocess: [False]
      maintain_gt_shape: [False]
  dataloader:
    num_workers: [16]
    batch_size: [1]
    csv_folder: [data_csv]

other_grids:
  - model: [dmtnet]
    explainer:
      name:
        [
          random,
          gaussian_noise,
          saliency,
          integrated_gradients,
          blur_ig,
          deep_lift,
          xrai,
          lime,
          affinity,
          masked_affinity,
          signed_affinity,
        ]