grid: IAUCDAUCMioU_Coco

parameters:
  model: [dcama]
  explainer:
    name: [affinity, saliency, random, integrated_gradients, deep_lift]

  explanation_masking: [logits]
  log_frequency: [50]

  metric:
    n_steps: [75]
    substrate_fn: [zero]
    measure: [miou]
    skip_empty: [True]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      val_coco20i_N1K5:
        name: [coco]
        instances_path: [data/coco/annotations/instances_val2014.json]
        all_example_categories: [False]
        img_dir: [data/coco/train_val_2017]
        n_shots: [5]
        n_ways: [1]
        do_subsample: [False]
        add_box_noise: [False]
        val_fold_idx: [null]
        n_folds: [null]
        split: ["val"]
    common:
      remove_small_annotations: [True]
      custom_preprocess: [False]
      maintain_gt_shape: [False]
  dataloader:
    num_workers: [16]
    batch_size: [1]
    csv_folder: [data_csv]

other_grids:
  -
    model: [dmtnet]
    explainer:
      name: [affinity, random, saliency, integrated_gradients]
    dataloader:
      num_workers: [16]
      batch_size: [1]
      csv_folder: [data_csv]
      num_processes: [10]