grid: CUTIAUCMioUCross

parameters:
  model: [dmtnet]
  explainer:
    name: [affinity, saliency, random, integrated_gradients]

  explanation_masking: [logits]
  # metric_masking: [all]
  log_frequency: [50]
  disable_dauc: [True]
  
  metric:
    n_steps: [1]
    substrate_fn: [zero]
    percentage: [0.01, 0.05]
    measure: [miou]
    loss: [True]
    skip_empty: [True]

  dataset: # parameters depending on the class you defined for the dataset
    datasets:
      -
        val_deepglobe_N1K1:
          name: deepglobe
          datapath: "data"
          split: "val"
          val_fold_idx: 0
          n_shots: 1
          n_ways: 1
          val_num_samples: 1000
      -
        val_isic_N1K1:
          name: isic
          datapath: data/ISIC_cls
          split: val
          val_fold_idx: 0
          n_shots: 1
          n_ways: 1
          val_num_samples: 1000
      -
        val_lung_N1K1:
          name: lung
          datapath: data
          split: test
          val_fold_idx: 0
          n_shots: 1
          n_ways: 1
          val_num_samples: 1000
    common:
      remove_small_annotations: [True]
      custom_preprocess: [False]
      maintain_gt_shape: [False]
  dataloader:
    num_workers: [16]
    batch_size: [1]
    csv_folder: [data_csv]
